repos:
- repo: https://github.com/returntocorp/semgrep
  rev: 'v0.37.0'
  hooks:
    - id: semgrep
      # See semgrep.dev/rulesets to select a ruleset and copy its URL
      args: ['--config', 'p/r2c-best-practices', '--error']
